version: '3.8'
services:
  postgres:
    container_name: atividade4-postgres-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: staging
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: