CREATE TABLE atividade2 (
    name TEXT,
    cnpj TEXT,
    segment TEXT,
    revenue TEXT,
    reviews_count BIGINT,
    culture_count BIGINT,
    salaries_count BIGINT,
    benefits_count BIGINT,
    culture_score DOUBLE PRECISION,
    diversity_score DOUBLE PRECISION,
    quality_of_life_score DOUBLE PRECISION,
    leadership_score DOUBLE PRECISION,
    compensation_score DOUBLE PRECISION,
    career_opportunities_score DOUBLE PRECISION,
    recommend_percent DOUBLE PRECISION,
    positive_outlook_percent DOUBLE PRECISION,
    match_percent DOUBLE PRECISION,
    name_reclamacoes TEXT,
    category TEXT,
    type TEXT,
    year TEXT,
    quarter TEXT,
    complaint_index TEXT,
    regulated_complaints_upheld TEXT,
    regulated_complaints_other TEXT,
    unregulated_complaints TEXT,
    total_complaints TEXT,
    total_clients_ccs_scr TEXT,
    clients_ccs TEXT,
    clients_scr TEXT,
    cnpj_reclamacoes TEXT
);